server:
  port: 9999

spring:
  application:
    name: customer-web
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1:8848}
        namespace: ${NACOS_SPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
  config:
    import:
      - optional:nacos:base.yaml
      - optional:nacos:customer-web.yaml
